package tugas;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import java.awt.*;
import javax.swing.Timer;
public class Tugas extends javax.swing.JFrame {

     Timer timer;
     int detik;
//     boolean ini = true;
     public Tugas() {
        initComponents();
        setTitle("Progam Timer");
        setLocationRelativeTo(null);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtmasukan = new javax.swing.JTextField();
        bhulang = new javax.swing.JButton();
        bberhenti = new javax.swing.JButton();
        bhitung = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel4.setText("jLabel4");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\BIMA\\OneDrive\\Gambar\\Saved Pictures\\iii.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELAMAT DATANG ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 231, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PROGAM HITUNG MUNDUR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 266, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\BIMA\\OneDrive\\Gambar\\Saved Pictures\\6.png")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 100, 90));

        txtmasukan.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtmasukan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtmasukan.setText("0");
        txtmasukan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtmasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmasukanActionPerformed(evt);
            }
        });
        txtmasukan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmasukanKeyReleased(evt);
            }
        });
        getContentPane().add(txtmasukan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 83, 42));

        bhulang.setText("ULANG");
        bhulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhulangActionPerformed(evt);
            }
        });
        getContentPane().add(bhulang, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 90, -1));

        bberhenti.setText("BERHENTI");
        bberhenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bberhentiActionPerformed(evt);
            }
        });
        getContentPane().add(bberhenti, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 100, -1));

        bhitung.setText("HITUNG");
        bhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhitungActionPerformed(evt);
            }
        });
        getContentPane().add(bhitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 80, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\BIMA\\OneDrive\\Gambar\\Saved Pictures\\iii.jpg")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bhulangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhulangActionPerformed
        timer.stop();
        detik = 0;
        txtmasukan.setText("");
    }//GEN-LAST:event_bhulangActionPerformed

    private void bberhentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bberhentiActionPerformed
        timer.stop();
    }//GEN-LAST:event_bberhentiActionPerformed

    private void txtmasukanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmasukanKeyReleased
        txtmasukan.getText();
        detik = Integer.parseInt(txtmasukan.getText());
    }//GEN-LAST:event_txtmasukanKeyReleased

    private void txtmasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmasukanActionPerformed

    }//GEN-LAST:event_txtmasukanActionPerformed

    private void bhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhitungActionPerformed
        timer = new Timer(1000, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                txtmasukan.setText(""+detik);
                detik++;

                if(detik <0){
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(null, "Waktu Telah Habis","Stop",0);
                    detik =0;
                    timer.stop();
                }
            }

        });
        timer.start();
    }//GEN-LAST:event_bhitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bberhenti;
    private javax.swing.JButton bhitung;
    private javax.swing.JButton bhulang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtmasukan;
    // End of variables declaration//GEN-END:variables
}
